from django.db import models

# Create your models here.
class Day(models.Model): 
    day_number = models.IntegerField(blank=True, null=True)
    oxygen = models.IntegerField(blank=True, null=True)
    propane = models.IntegerField(blank=True, null=True)
    copper_raw = models.IntegerField(blank=True, null=True)
    copper_rings_raw = models.IntegerField(blank=True, null=True) 
    copper_tubing = models.IntegerField(blank=True, null=True)
    berylium_raw = models.IntegerField(blank=True, null=True)
    brass_raw = models.IntegerField(blank=True, null=True)
    silver_solder = models.IntegerField(blank=True, null=True)
    grinding_wheels = models.IntegerField(blank=True, null=True)
    machine_tools = models.IntegerField(blank=True, null=True)
    copper_first_op = models.IntegerField(blank=True, null=True) 
    copper_second_op = models.IntegerField(blank=True, null=True) 
    copper_third_op = models.IntegerField(blank=True, null=True)
    copper_first_inspection = models.IntegerField(blank=True, null=True)
    copper_second_inspection = models.IntegerField(blank=True, null=True)
    copper_third_inspection = models.IntegerField(blank=True, null=True)
    copper_first_op  = models.IntegerField(blank=True, null=True)
    copper_second_op = models.IntegerField(blank=True, null=True)
    copper_third_op = models.IntegerField(blank=True, null=True)
    copper_first_inspection = models.IntegerField(blank=True, null=True)
    copper_second_inspection = models.IntegerField(blank=True, null=True)
    copper_third_inspection = models.IntegerField(blank=True, null=True)
    copper_prebrightdip = models.IntegerField(blank=True, null=True)
    copper_postbrightdip = models.IntegerField(blank=True, null=True)
    brass_first_op = models.IntegerField(blank=True, null=True)
    brass_second_op = models.IntegerField(blank=True, null=True)
    brass_prebrightdip = models.IntegerField(blank=True, null=True)
    brass_postbrightdip = models.IntegerField(blank=True, null=True)
    berylium_first_op = models.IntegerField(blank=True, null=True)
    berylium_second_op = models.IntegerField(blank=True, null=True)
    berylium_third_op = models.IntegerField(blank=True, null=True)
    berylium_first_inspection = models.IntegerField(blank=True, null=True)
    berylium_second_inspection = models.IntegerField(blank=True, null=True)
    berylium_third_inspection = models.IntegerField(blank=True, null=True)
    berylium_prebrightdip = models.IntegerField(blank=True, null=True)
    berylium_postbrightdip = models.IntegerField(blank=True, null=True)
    copper_rings_op = models.IntegerField(blank=True, null=True)
    copper_rings_prebrightdip = models.IntegerField(blank=True, null=True)
    copper_rings_postbrightdip = models.IntegerField(blank=True, null=True)
    silver_solder_firstop = models.IntegerField(blank=True, null=True)
    first_grinding_op = models.IntegerField(blank=True, null=True)
    silver_solder_secondop = models.IntegerField(blank=True, null=True)
    second_grinding = models.IntegerField(blank=True, null=True)
    finish_machining_firstop = models.IntegerField(blank=True, null=True)
    finish_maching_secondop = models.IntegerField(blank=True, null=True)
    deburr = models.IntegerField(blank=True, null=True)
    finishing = models.IntegerField(blank=True, null=True)


    def __int__(self):
        return self.day_number