# Generated by Django 3.2.9 on 2021-11-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='berylium_first_inspection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='berylium_first_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='berylium_postbrightdip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='berylium_prebrightdip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='berylium_raw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='berylium_second_inspection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='berylium_second_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='berylium_third_inspection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='berylium_third_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='brass_first_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='brass_postbrightdip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='brass_prebrightdip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='brass_raw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='brass_second_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='copper_first_inspection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='copper_first_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='copper_postbrightdip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='copper_prebrightdip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='copper_raw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='copper_rings_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='copper_rings_postbrightdip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='copper_rings_prebrightdip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='copper_rings_raw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='copper_second_inspection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='copper_second_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='copper_third_inspection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='copper_third_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='copper_tubing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='deburr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='finish_maching_secondop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='finish_machining_firstop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='finishing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='first_grinding_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='grinding_wheels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='machine_tools',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='oxygen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='propane',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='second_grinding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='silver_solder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='silver_solder_firstop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='silver_solder_secondop',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
